version: '3.1'

services:
  odoo:
    image: odoo:12
    restart: always
    ports:
      - "8069:8069"
    environment:
      DB_HOST: "roundhouse.proxy.rlwy.net"
      DB_PORT: "41835"
      DB_USER: "postgres"
      DB_PASSWORD: "cJgQzjWqlWbcojdfgIvEtmCcFJIRoTJo"
      DB_NAME: "railway"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/custom_addons:/mnt/extra-addons

volumes:
  odoo-web-data:
