version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cJgQzjWqlWbcojdfgIvEtmCcFJIRoTJo
    ports:
      - "5432:5432"

  odoo:
    image: odoo:12
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres.railway.internal
      - USER=postgres
      - PASSWORD=cJgQzjWqlWbcojdfgIvEtmCcFJIRoTJo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/custom_addons:/mnt/extra-addons

volumes:
  odoo-web-data:
