version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cJgQzjWqlWbcojdfgIvEtmCcFJIRoTJo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Exposing 5432 is optional; remove if not needed
    ports:
      - "5432:5432"

  odoo:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - USER=postgres
      - PASSWORD=cJgQzjWqlWbcojdfgIvEtmCcFJIRoTJo
      - DATABASE=railway
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/custom_addons:/mnt/extra-addons

volumes:
  postgres-data:
  odoo-web-data:
